### ISSUE TITLE
Configure ssh port?

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#1039]
Is there an easy way to change the sshd listen port / bind ip?

Would be nice to have port 22 available for applications  :)

**Comment by cmavr8** [comment]
It should be possible since November 2015: https://forums.rancher.com/t/change-the-default-sshd-port/859

**Comment by pwFoo** [comment]
That looks like a workaround. A clean solution is prefered (in the future).

**Comment by StevenCaminada** [comment]
Id wanted to ask if and where the clean solution is available. Thank you

**Comment by pwFoo** [comment]
Any update here?
Custom sshd port and / or listen ip (internal management interface / ip address) would be nice.

**Comment by JasonGiedymin** [comment]
Knowing that upon first boot, login is auto until `cloud-config` is installed, I don't see anything wrong with specifying `write_files:` for `sshd_config`. To me the semantics of keeping all the configs in cloud-config is totally acceptable and this message remains consistent.

If you want to change something on the os, start with `cloud-config`. Currently I have my own settings for network interfaces and sshd sitting in a `cloud-config`.

Baring implementation opinions, this ticket could be closed because you in fact can change the port with `write_files`.

**Comment by klud1** [comment]
`write_files` is a clean solution, but I can't pass the `cloud-config` file when creating instances with `docker-machine` on GCP.

**Comment by JasonGiedymin** [comment]
This might be a limitation of the docker-Machine driver as well as google only allowing cloud-init with cos based images (google cloud containerized OS). 

I recommend setting up a local vpc box that can serve these files. You could get these files remotely from the server being set up. Albeit not automated.

Otherwise you could create a custom image with knowledge of said bootstrap server. 

-Jason

**Comment by niusmallnan** [comment]
I will support these configurations:
```
rancher:
  ssh:
    port: 10022
    listen_address: 172.22.100.100
```
Users can use these in the cloud-config file.

**Comment by kingsd041** [comment]
Tested with rancheros-v1.3.0-rc1.
In v1.13.0-rc1, configuring ssh port and listenaddress in cloud-config is already supported
