### ISSUE TITLE
Custom RancherOS ISO docs refer to updating nonexistant /build.conf

### ISSUE THREAD

**Issue by hh** [rancher/os#1049]
From http://docs.rancher.com/os/configuration/custom-rancheros-iso/:

```
In the root of the repository, the build.conf file can be updated
for changes for custom kernels, or custom docker.
```

However I can't locate that file in a [rancher/os search for a build.conf file](https://github.com/rancher/os/search?utf8=%E2%9C%93&q=filename%3Abuild.conf) in the current master. I'm guessing it was removed at some point.

**Comment by joshwget** [comment]
You're correct, we refactored our build process recently and `build.conf` was removed. We have a set of updates to the docs for the upcoming v0.5 release that haven't been made live yet. Part of these changes include [updated docs on building a custom ISO](https://github.com/rancher/rancher.github.io/blob/OSv050/os/configuration/custom-rancheros-iso/index.md). These will be on the main docs site once v0.5 is released.

**Comment by deniseschannon** [comment]
When we merge in the docs branch for v0.5.0, I'll close this issue.

**Comment by deniseschannon** [comment]
I'm going to close this issue now and when v0.5.0 is released, if you still have questions, please open a new issue.

**Comment by xlCHINCHlx** [comment]
So that's why I cant find build.conf. . . 

Also the os-kernel repo will only pull your kernel source and match the hashes correctly if the kernel source file name is the last text in the https link.For instance, I uploaded my kernel to drive (https://drive.google.com/file/d/0BxHUHpxqYFwcTUhncmV2aC1ZYnM/view?usp=sharing) and it couldn't curl the file and check the sum correctly.

Anyways, just a heads up.
Thanks for all your hard work, looking forward to the release of v0.5.0.

**Comment by deniseschannon** [comment]
@xlCHINCHlx Can you file a new issue for your kernel source issue? Otherwise, we might miss addressing your issue.
