### ISSUE TITLE
Starting v0.5.0-rc1 with docker-machine results in having my ssh key duplicated 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/os#1062]
**RancherOS Version: (ros os version)**
v0.5.0-rc1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

Launched v0.5.0-rc1 using docker-machine, when doing a `sudo ros config export`, I noticed my ssh keys were duplicated. Tracked it down to `/var/lib/rancher/conf/cloud-config.d/machine.yml`. In that file, my keys are duplicated.

**Comment by joshwget** [comment]
Based on the code responsible for handling Docker Machine, this seems to be intentional.
```yaml
ssh_authorized_keys:
 - ${AUTHORIZED_KEY1}
 - ${AUTHORIZED_KEY2}
```
These two keys just happen to be the same in this case. I'm guessing Docker Machine allows customizing the second SSH key or something like that.

Previous releases had the same thing in `/var/lib/rancher/conf/cloud-config.d/machine.yml`. I think the difference is that `ros config export` now shows values from `/var/lib/rancher/conf/cloud-config.d/`.

We can leave this open to make sure that `AUTHORIZED_KEY2` is still necessary, but it's always been like this so the duplicated key shouldn't cause any issues.
