### ISSUE TITLE
Can not booting RancherOS via iPXE

### ISSUE THREAD

**Issue by datawolf** [rancher/os#1088]
**RancherOS Version: (ros os version)**

v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

virtualbox

I can not booting RancherOS via iPXE with the following step:

```
#!ipxe
# Boot a persistent RancherOS to RAM

# Location of Kernel/Initrd images
$ set base-url http://releases.rancher.com/os/latest

$ kernel ${base-url}/vmlinuz rancher.state.autoformat=[/dev/sda] rancher.cloud_init.datasources=['url:http://192.168.1.100/cloud-config']
$ initrd ${base-url}/initrd
$ boot
```

It seems that the function `LoadConfig()` parse `rancher.cloud_init.datasources=['url:http://192.168.1.100/cloud-config']` error.

**Comment by Moeser** [comment]
I'm having this same problem with our pxe boot image to 0.5.0.  If I remove the cloud_init datasource then the image boots fine.

**Comment by Moeser** [comment]
I can help test this if there's a updated/nightly build of the pxe image somewhere.

**Comment by deniseschannon** [comment]
@datawolf Can you test this out with v0.6.0-rc1 and let me know if you have any issues?

**Comment by imikushin** [comment]
in v0.6.0 the following syntax works for this kind of kernel parameters:
`rancher.cloud_init.datasources='["url:http://10.0.2.2:8800/cc.yml"]'` 

The param value is a YAML list. Single quotes are not part of the value, but effectively pass what's between them **as is**. The double-quotes in the value are needed so that the string with `:` is read as string (not as map).
