### ISSUE TITLE
rancher-agent in cloud-config can't access rancher-server api

### ISSUE THREAD

**Issue by ShiroiKuma** [rancher/os#1101]
**RancherOS Version: (ros os version)**
OS v0.5.0
Server v1.1.0
Agent v1.0.2

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

RancherOS on KVM
Tested VirtualBox too

Using the example Rancher on Rancher OS guide's example cloud-config, add a new host and add the correct keys to cloud-config. Reboot the server and notice there is no host.

Check docker agent logs and notice warnings that it can't connect to the v1 api.

Manually running sudo docker run method works, but only until a reboot. docker exec -it into the container and curl the URL and it connects fine to the api. 

This was working perfectly on v0.4.5. Could it be the registration token is being lost on reboot?

**Comment by deniseschannon** [comment]
Just to clarify, the host showed up originally when you first booted the RancherOS hosts. And then you rebooted the server and the host goes into reconnecting? 

Can you share your cloud-config (hiding the sensitive information)?

**Comment by ShiroiKuma** [comment]
Sorry for the extreme delay. I'll try and get the cloud-config file shortly for you. But to clarify this seems to only be an issue when running adding the the Host as a node.

By moving to using Rancher and Rancher-Agent on two separate VM's it worked perfectly, and no issues have occurred since.

It only a problem doing both on the same server, against best practices.

**Comment by deniseschannon** [comment]
@ShiroiKuma If you can share your cloud-config and still have an issue, please reopen.

Like you mentioned it's against best practices to have rancher server and agent running on the same host. I also don't think this is possible if you are trying to start Rancher and add a host in the same cloud config due to the host registration/token requirements that need to be generated after launching Rancher server before adding a host.
