### ISSUE TITLE
Unable to run `system-docker network` commands on v0.5.0

### ISSUE THREAD

**Issue by ryansch** [rancher/os#1104]
**RancherOS Version: (ros os version)**
v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
AWS

If I boot a clean v0.5.0 AMI on AWS and attempt to run any `system-docker network` commands I get back the following error: `Error response from daemon: 404 page not found`

**Comment by ryansch** [comment]
Notably these commands work fine on v0.4.5.

**Comment by ibuildthecloud** [comment]
This is because system docker does not have libnetwork.  Basically Docker has gotten too big for our uses as a system manager.  As such with 0.5 we have shipped a trimmed down docker for PID 1.  The noticeable differences are no libnetwork (uses CNI instead), no swarm/discovery, and embedded containerd/shim (not separate processes).

The intention is that it should behave just the same as a full blown docker but largely removes the weight of all the new clustering/orchestration bits that Docker has added.

We a looking for feedback from the community on this change.  The net result is that our slimmed down Docker uses far less memory.  I don't have have the exact numbers but it was close to half as small.

**Comment by ryansch** [comment]
That's really interesting.  I'll experiment with moving my system services over to user docker.  I might be making some headway against #1093 with these changes.

**Comment by ryansch** [comment]
Moving everything to user docker worked great.  Might be nice to have some of this intent stuff documented in an upgrade guide.
