### ISSUE TITLE
Can't remove a key in cloud-config

### ISSUE THREAD

**Issue by scls19fr** [rancher/os#1187]
**RancherOS Version: (ros os version)**
v0.5.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
baremetal @ home

I did a small mistake (confusing `adress` (which is close to french word `adresse` and `address` in my `cloud-config.yml` file
and now after fixing it I get

````
$ sudo ros config export
hostname: serv4u
rancher:
  network:
    dns:
      nameservers:
      - 192.168.1.1
    interfaces:
      eth*:
        dhcp: false
      eth0:
        address: 192.168.1.5/24
        adress: ""
        dhcp: false
        gateway: 192.168.1.1
        mtu: 1500
ssh_authorized_keys:
- ssh-rsa AAAA==  me@domain.com
```

I can't remove `adress` 

I tried

```
sudo ros config delete rancher.network.interfaces.eth0.adress
```

but it raises

```
No help topic for 'delete'
```

I also tried

```
sudo cat /var/lib/rancher/conf/cloud-config.yml | grep adress
```

and see that this key is not present in this file!

that's very odd!


How can I remove this key ?

**Comment by joshwget** [comment]
All configuration files other than `/var/lib/rancher/conf/cloud-config.yml` are located in `/var/lib/rancher/conf/cloud-config.d/`. It's likely that the misspelled key is located in a file somewhere in that directory.

The `ros config delete` command doesn't actually exist. Since configuration is split across different files, deletion is a somewhat undefined operation.

**Comment by scls19fr** [comment]
Thanks that's fixed!
