### ISSUE TITLE
`ros service delete` doesn't remove the container

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#1296]
**RancherOS Version: (0.7 ~dev)**

**Where are you running RancherOS? (qemu, thinkpad)**

and so if you re-enable it, that container will get re-used. This is more of an issue if the service definition has changed, as those changes won't be picked up.

**Comment by joshwget** [comment]
I can definitely see the confusion here. The problem is that there are two types of operations under the `ros service` subcommand. There are the commands that deal with service configurations (`ros service enable`, `ros service list`, `ros service disable`, and `ros service delete`) and then the standard Docker Compose commands.

To actually delete a container you'd use `ros service down` or `ros service rm`. It's a little confusing, but I'm not sure of a better way of handling it.

I don't know if the second point is true though. If you change a service definition it should also recreate the container like Docker Compose.

**Comment by SvenDowideit** [comment]
ok, so we need to work towards simplifying the `ros` command - the help tells me nothin:

```
     delete   delete a service
...
     rm       Delete services
```

dunno that its urgent, just important :)

**Comment by joshwget** [comment]
Do you mean doing something like `ros config set rancher.console ubuntu`? At least for this case it's intentional that you're able to do this. What kind of weird errors does it lead to?
