### ISSUE TITLE
Not able to ssh into iso boot to upload cloud-config.yml

### ISSUE THREAD

**Issue by HansHammel** [rancher/os#1340]
When booting RacherOS Stable 0.7.0 ISO in VM (ESXi 5.5 using vSphere) I am unable to login via ssh/scp (Putty, WinSCP). I tried combinations of rancher/rancher, racher/passowrd, rancher/- and even root. I cannot login to upload/past the cloud-config.yml file/content before disk installation. very annoying. please update the docs how to get the config files into a vm. typing rsa keys by hand is no option! or get the vmware tools working for clipboard support...

**Comment by joshwget** [comment]
Do you have console access for this host? If so, you can change the password and then SSH.

**Comment by HansHammel** [comment]
I do and manged to install it some other way, but I think it's an issue esp. for bare metal production installations...

**Comment by Paulmicha** [comment]
I'd argue that the possibility NOT to use SSH keys to login (i.e. provide simple default password when using `ros install -d /dev/sda`) is not just convenient : it's blocking quick & simple local tests e.g. using VirtualBox...

![virtualbox-rancher-os-after-install--useless](https://cloud.githubusercontent.com/assets/1526964/19895125/acb34c58-a036-11e6-8bb3-aafae0083ae7.png)

Unless I've missed something ?

**Comment by Coada** [comment]
Bump. I am trying to automate setup of a Rancher OS system and need to SSH into the VM after it has booted from ISO. rancher/rancher, rancher/ does not work. Yes I could access the console manually, but that removes the purpose of automating.

Is there perhaps possible to modify the ISO to set a default password?

**Comment by niusmallnan** [comment]
@Coada You can set rancher password with a kernel parameter.
```
ros install -d xxx --append  rancher.password=xxxx
# or
ros os upgrade --append rancher.password=xxx
```

**Comment by zopar** [comment]
@niusmallnan you can do that when you can login on the system. Coada want to automate the installation, so he need to boot the system from the iso, login automatically and do the ros install. If you can't login you can't install and set the ros password. I not understand why the ssh login on boot from iso is disabled. Anyway it seems that the only option to enable login after iso booting is to create a specific rancheriso with the rancher.passowrd set, because is not possible to automatically pass to grub the rancher.password option to the kernel. Please in the next iso, create the ability to login via ssh after boot.

**Comment by zopar** [comment]
For system like vmware, you could build rancheriso with rancher.password=rancher for grub. In a vmware system I think is the best choice, because normally you can't access the vm console without vcenter credential, so we do not need to disable password for the first boot from iso. This will permit to auotmate installazion on vmware without using docker-manchine that have also some problems in vmware.

**Comment by Coada** [comment]
Yes, zopar explained my problem nicely. I managed to work around the problem by creating the ISO with a set password; we already had a pipeline that was building the ISO from scratch so it was a relatively trivial task.

**Comment by zopar** [comment]
I think we can define vmware as "special" case. 
Who works on it needs sometime to install without internet connection, so we need ad iso with everything inside.
Another thing is maybe to create an OVA the cloud-config method with iso is not really handy for large deployment on vmware. This could be achived if ros could reapply a cloud-config.yaml also after a basic installation without needs to erase the disk

Whit this 3 improvement I think will be really easy to deploy on vmware. Do not understimate that many people uses vmware in private datacenter.

**Comment by niusmallnan** [comment]
We have supported ISO and vmdk artifacts, and ros can get config data via `vmware-guest-info`.
Most people will use `cloud-init.config.data`.

https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/cloud/vmware-esxi/

**Comment by chambodn** [comment]
Does anyone try to configure rancheros iso via ansible and vmware_guest module? How could you specify `cloud-init.config.data` at startup?

**Comment by chambodn** [comment]
My bad, I found the answer... This is working for me:
```yaml
customvalues:
  - key: guestinfo.hostname
    value: myhostname
```
