### ISSUE TITLE
Version of system-docker

### ISSUE THREAD

**Issue by SamMousa** [rancher/os#1383]
**RancherOS Version: (ros os version)**
v0.7.0

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
VirtualBox

I was doing some experimenting with RancherOS and wanted to check the version of the system-docker daemon. It returned: "library-import". This makes it impossible for the normal docker client to interact with the system-docker daemon. (Imagine if I wanted to mount `/var/run/system-docker.sock:/var/run/docker.sock` into some container that does something with the docker engine.

After some research I found this: https://github.com/rancher/docker/blob/master/dockerversion/version_lib.go#L7

Is it a deliberate choice to not set a version for the system-docker daemon?

**Comment by ibuildthecloud** [comment]
The system-docker daemon is a very, very custom version of Docker based off 1.11.  We should probably set the version on it.  If you were to start using it more you would find somethings different, namely libnetwork doesn't exist.  The main reason we did this is because with Docker 1.11+ the daemon was separated into docker, containerd, and containerd-shim.  These additional processes added a lot of memory overhead.  We modified Docker 1.11 to embed all the processes back into one.  While it worked for Docker 1.11, it is too difficult to continue to maintain that for each new Docker version.  As a stop gap I think we will roll system-docker back to Docker 1.10.3, which was really the best version of Docker anyhow.  We have a different path forward in which we will focus system-docker more on containerd and runc, forgoing much of docker (libnetwork, swarm, etc) to continue to be lightweight.  That will take a bit more time to develop.

**Comment by ibuildthecloud** [comment]
I've created an issue for this https://github.com/rancher/os/issues/1394, to rollback to 1.10.3.  In the meantime if you have trouble talking to the docker socket either use `DOCKER_API_VERSION` to force the client to a version `export DOCKER_API_VERSION=1.22`, or do the same in the client code.

**Comment by SamMousa** [comment]
So, from a practical point, is the conclusion that I should not actually try to use system-docker?
Since it is not a "default" docker and in the future might not be docker at all?

**Comment by ibuildthecloud** [comment]
No, you are free to use it.  Even if we change it to something else we will keep compability with Docker and will be OCI complaint.  I just wanted you to know that it is different.
