### ISSUE TITLE
open-vm-tools container can go back to using Alpine

### ISSUE THREAD

**Issue by lucymhdavies** [rancher/os#1485]
A while ago, we moved to using Ubunto for the open-vm-tools service container.

https://github.com/rancher/os-services/blob/master/images/10-openvmtools/Dockerfile

```
FROM ubuntu:16.10
# FROM arm=skip arm64=skip
RUN apt-get update \
    && apt-get install -y open-vm-tools \
    && rm -rf /var/lib/apt/*
```

This was due to the following issue in Alpine:
https://bugs.alpinelinux.org/issues/5487

This is now fixed, and will be available in Alpine 3.5.1.

Once that is released (within a month, by the looks of their release schedule), we can switch back to using Alpine for this container, which should shrink it down a bit :)

**Comment by joshwget** [comment]
I can't seem to find the thread, but I remember reading that open-vm-tools is designed to be used with glibc. I'm a little hesitant to switch back to musl (Alpine) because of this. It might just be a matter of time before another pretty major issue like this pops up.

As part of #1478 I've been working on an open-vm-tools package. It's based on glibc while still being around the same size as the Alpine based image. It'll also be able to reuse os-base as a base image in the future which will save even more space.

**Comment by lucymhdavies** [comment]
ah, cool. In which case, that sounds like a better idea :)

**Comment by joshwget** [comment]
Created #1487 so we can still track this. Thanks @lucymhdavies!
