### ISSUE TITLE
Kernel parameters (e.g. rancher.password) are readable by any user-docker container

### ISSUE THREAD

**Issue by janeczku** [rancher/os#1537]
We should clearly document that passing sensitive configuration options, e.g. `rancher.password` as kernel arguments poses a security issue, as even unprivileged containers with dropped capabilities have read access to the host's kernel command line.

```
[root@rancher ~]# docker run -it --rm --cap-drop=ALL alpine:3.5 /bin/sh
/ # cat /proc/cmdline
rancher.password=a_password_everyone_can_see
```

Besides the rancher password, there are other configuration parameters like `cloud_init.datasources` that admins may not want to expose to user containers as well. We should evaluate how access to host kernel cmdline can be blocked for unprivileged containers.

**Comment by SvenDowideit** [comment]
I'm not sure how much we can do about this, so it might become a docs only thing, but 👍

**Comment by janeczku** [comment]
Proposed fix:

1. Update Docker SELinux policy to block access to host`s `/proc/cmdline` from containers
2. Document that when users are passing sensitive information as kernel parameter they should enable SELinux for the user docker.

**Comment by SvenDowideit** [comment]
The other proposal we've discussed is to add filtering into system-docker.

**Comment by janeczku** [comment]
@SvenDowideit Checking with customer which proposal meets his requirements

**Comment by janeczku** [comment]
The requirement is:
1. Block access to the content of the host's `/proc/cmdline` as a whole for user docker containers.
2. `/proc/cmdline` still needs to be readable by any system-docker container (e.g. console)

**Comment by SvenDowideit** [comment]
ok, so I think blocking /proc/cmdline entirely would be a custom option - the normal operation (for maximum compatibility) would be to provide a /proc/cmdline that has the `rancher.*` keys filtered out.

**Comment by SvenDowideit** [comment]
alright, I've now had a few different attempts at this, and patching the kernel is the only real option. using a regexp to filter parameters has too much risk, so what I'm trying is to blank out the arguments that are ignored by the kernel - the ones that come after a double dash: `--`. These are passed to the init process as arguments, so RancherOS can recover them from there, without them being exposed to containers.

blanking `/proc/cmdline` has random side effects - including just causing some processes to not start, so that really won't work.

The other option (which can't happen quickly) is to get a change into runc that switches the /proc/cmdline with a filtered version - (I tried this on system-docker, but it doesn't carry over to user-docker) - but this can be undone by the user of a privileged container, as its a container local bind-mount.

**Comment by deniseschannon** [comment]
In v0.9.0-rc1

All containers (including ones in system-docker) are denied permissions to `/proc/cmdline`

@janeczku Would that be sufficient or we need to figure out how to get access for system docker containers?

**Comment by deniseschannon** [comment]
@SvenDowideit I spoke with @janeczku and system docker containers must be able to access this information.

**Comment by SvenDowideit** [comment]
no container is denied permission to /proc/cmdline - that causes some processes to crash - each container gets a new procfs. we can only remove things in the kernel during the boot process.

#1678 hasn't been merged yet - I still need more information / discussion to find out what kind of UX is possible.
