### ISSUE TITLE
Ros install fails with name drive

### ISSUE THREAD

**Issue by jaknoll** [rancher/os#1753]
**RancherOS Version: 0.9.2-rc1**

**Where are you running RancherOS? Baremetal

Booting from iso fails, the install fails immediately with an name drive.  See my post on the forum for more detail: 
https://forums.rancher.com/t/rancheros-fails-to-install-on-nvme-drive/6076

**Comment by jaknoll** [comment]
Oops, meant to say:  booting from the I so, the install fails...

The boot from I so works fine

**Comment by SvenDowideit** [comment]
[quote="Jon_Knoll, post:1, topic:6076"]
-d /dev/nvme0n1
[/quote]

the `-d` device is the unpartitioned device, and the installer will then try to create a partition `/dev/nvme0n11` and install to it.

if you have already created the partition, then the install will fail.

There is a `-p` option (iirc), so you can use both `-d` and `-p` - but that might be something i just fixed in the upcoming 0.9.2 release. (sorry, I'm on holidays in rural Tasmania, so not entirely sure atm)

**Comment by jaknoll** [comment]
ended up installing successfully with -p and v1.0.1-rc1.  Unfortunately, could not get my bios to recognize an nvme device as bootable.
