### ISSUE TITLE
about default account and password

### ISSUE THREAD

**Issue by fengzhibin** [rancher/os#1980]
**RancherOS Version: (ros os version)**
1.0.3

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
virtualbox

When I start through ISO, the racher user cannot log on through the password. But the online tutorial says it's the first time you install it, you can log in through a password. Is it because of versioning?

I'm making a tool like boot2docker, and I use rancheros.iso as a mirror image. I want to go through the SSH to the machine, and then do some initialization configuration. Can the 1.0.3 version rancheros be configured from the remote machine SSH?

**Comment by SvenDowideit** [comment]
@fengzhibin which online tutorial?

We've removed the default password (except on arm) because its very insecure - its too easy for users to leave the default in place, and forget to change it.

instead, we have a number of ways to set ssh keys - the cloud-init file being the most standard one, and docker-machine and boot2docker use a magic marker written to the disk, with an added tar file containing the initial contents for the user dir - thus allowing ssh access.

Additionally, RancherOS auto logs on as `rancher` into both `tty1` and `ttyS0` (and probably `ttyS1` soon.

**Comment by fengzhibin** [comment]
@SvenDowideit 
I see the password for rancheros users from third party websites. Probably the old version.My question has been settled.OK.Thanks.

**Comment by fengzhibin** [comment]
@SvenDowideit 
Did you know the first installation of boot2docker.iso?. How does it bypass SSH authentication?
I'm trying to read docker-machine's source code. But I don't understand the go language, and I seem to see it through the cert certificate. But I through Google search engine, but can't find the relevant information. Can you tell me the relevant information?
I want to do a one click Install LNMP environment software. Through docker implementation, it turned out to be CentOS as a virtual machine system. But the CentOS system is too big to spread easily. So I use rancheros as the virtual machine system and install the LNMP environment through docker. Packaged into integrated script execution. Now, because rancheros does not have the default password, the first installation can not be connected from the outside to the virtual machine via the ssh.
