### ISSUE TITLE
WIP: Replace system-docker with runc and containerd

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/os#2078]
system-docker was made before runc and containerd were extracted from Docker - and they're essentially the same idea.

My current idea is to use `runc` for the pre-switchroot initialisation containers, and then to use containerd for the longer running system containers (so we can fetch images)

- [ ] start bootstrap and cloud-init-save and the recovery console using runc
- [ ] add a `rancher.recovery.after=<servicename>` so we can start the recovery console at a specific point in the boot (and make it so it can run both inside and outside a container?)
- [ ] add a simplified composefile related API for containerd and use it to replace system-docker
- [ ] replace the image.tar file with a linuxkit style runc/containerd dir
- [ ] generalise runc exec : #1220

**Comment by allingeek** [comment]
Since this is in the v1.2.0 milestone will this change maintain a consistent user-interface (i.e. the system-docker command). It seems to me that if the intention is to replace feature implementations build using custom components with reusable ones that doing so would be possible. Even if this looks like some kind of alias or facade I think it would be worth maintaining the interface until a major release. The documentation change long tail would be a nightmare otherwise.
