### ISSUE TITLE
User docker storage_driver is cached in /var/lib/rancher/conf/docker

### ISSUE THREAD

**Issue by ryansch** [rancher/os#2317]
**RancherOS Version: (ros os version)**
v1.3.0
**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
docker-machine

Since docker-machine doesn't give us a way to do could config when setting up a VM, I have to change configuration after the first full boot and then perform a reboot.  I discovered that I could not get user docker to use overlay2 until I found the overlay setting was cached in /var/lib/rancher/conf/docker.

Working config:
```
ros config set rancher.docker.storage_driver overlay2
sed -ie 's/storage-driver overlay/storage-driver overlay2/' /var/lib/rancher/conf/docker
```

**Comment by Jason-ZW** [comment]
@ryansch This command can make user-docker using 'overlay2' storage-driver:
```
docker-machine create -d virtualbox  --engine-opt "storage-driver overlay2" --virtualbox-memory=2048 --virtualbox-boot2docker-url file:///Volumes/BOOTCAMP/rancheros-vmware.iso rancheros
```

Maybe it's not the best way but can resolve this issue.
After Startup the `/var/lib/rancher/conf/docker` change as below:
```
DOCKER_OPTS='
-H tcp://0.0.0.0:2376
-H unix:///var/run/docker.sock
--storage-driver overlay
--tlsverify
--tlscacert /var/lib/rancher/conf/ca.pem
--tlscert /var/lib/rancher/conf/server.pem
--tlskey /var/lib/rancher/conf/server-key.pem
--label provider=virtualbox
--storage-driver overlay2
'
```

@JacieChao 
It's best to find a way to solve the repeating fields, although I don't think it's important.

**Comment by ryansch** [comment]
I'll give that a try.  I didn't know `--engine-opt` was a thing!

**Comment by niusmallnan** [comment]
We should update the provisioning logic in docker-machine, It hasn't been updated for a long time.
https://github.com/docker/machine/blob/master/libmachine/provision/rancheros.go

The following features need to be re-supported:
1. Support  using `overlay2` via `--engine-storage-driver` flag
2. The  `versionsURL` value should be updated, users can use the latest RancherOS version.
3. The `isoURL ` value should be updated, we already do not support any `machine-rancheros.iso`.
4. No `rancherctl`, should use `ros` instead of it.
5. Some others need to be updated. Finally, I can get someone test it again.

**Comment by JacieChao** [comment]
We have updated the RancherOS provision in docker-machine. Wait for merging. After that, we could use `--engine-storage-driver` flag to config docker storage driver.
