### ISSUE TITLE
open-vm-tools balloon memory driver not working right in ROS

### ISSUE THREAD

**Issue by jambajaar** [rancher/os#2335]
We have concerns regarding the open-vm-tools balloon memory driver not working right in ROS (1.1.3).
Is this a defect?

We have vSphere hosts with 93% memory consumed, and we're surprised the balloon driver hasn't flushed the guests. We have a lot of memory on them that is not active.

$ sudo system-docker exec -ti open-vm-tools vmware-toolbox-cmd stat balloon 
0 MB

The underlying vsphere host this ran on currently has 93% memory consumption. The guest active memory is perhaps 20% but it's holding onto all 100% from the vsphere host (hence the balloon driver should kick in at some point to free pages).

When should the balloon driver should kick-in .. we would have expected it to start before the vsphere memory alerts started to go off.

**Comment by niusmallnan** [comment]
I didn't try Rancher v1.1.3, but try v1.4.0-rc2, we have shipped an ISO for [vmware](https://github.com/rancher/os/releases/download/v1.4.0-rc2/rancheros-vmware.iso). Looks like the balloon memory driver can work fine.
Here are my steps:

1. Boot an ESXi 6.5 host. The less host memory, the easier it is to observe balloon.
2. Create multiple VMs so that host memory usage exceeds 90%
3. Observe the host memory consumed by each VM, If the value changes(usually decreases), then check the balloon stat on this VM.

If it goes well, you can see the change of balloon memory:
```
$ sudo system-docker exec -ti open-vm-tools vmware-toolbox-cmd stat balloon
1070 MB
```
