### ISSUE TITLE
Memory requirements for each platform

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2359]
We should test and confirm the minimum memory requirements for each platform, please refer to the following table:

platform | RAM requirement | Note
---- | ---- | ----
VirtubalBox | 1024MB
VMWare | xxMB (without open-vm-tools) <br> xxMB (with open-vm-tools)
Hyper-V | xxMB
GCE |  xxMB
AWS |  xxMB

**Comment by kingsd041** [comment]
@niusmallnan  The minimum memory requirements for each platform please see the following table. Also because we don’t Hyper-V environment so will test it later once got the environment

platform | RAM requirement | Note
---- | ---- | ----
VirtubalBox | 1024MB
VMWare | 1024MB (without open-vm-tools) <br> 2048MB (with open-vm-tools)
Hyper-V | xxMB
GCE |  1024MB
AWS |  1.7G

**Comment by chriswayg** [comment]
1024 MB on VirtualBox is not enough when using 1.4.0-rc2, but was still still sufficient using 1.4.0-rc1, see https://github.com/rancher/os/issues/2372

**Comment by Toonix** [comment]
crashes on vmware with 1024M

**Comment by superseb** [comment]
These are the current requirements:

Platform | RAM requirement
-- | --
Baremetal | 1280MB
VirtubalBox | 1280MB
VMWare | 1280MB (rancheros.iso) 2048MB (rancheros-vmware.iso)
GCE | 1280MB
AWS | 1.7GB
