### ISSUE TITLE
[RFE] Allow alternate usernames to be entered when creating an ROS VM on Azure

### ISSUE THREAD

**Issue by mak3r** [rancher/os#2743]
**RancherOS Version: (ros os version)**
v1.5.1

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**
Azure

When creating instances on Azure using ROS, the user is prompted to enter the username that will be used with ssh to authenticate into the OS. The only username that works with RancherOS at this time is `rancher`. 

This is a request to allow the username to be specified as something other than `rancher`

**Comment by Jason-ZW** [comment]
### RancherOS on Azure
`Azure` using `Microsoft Azure Linux Guest Agent(waagent)` manages Linux provisioning and VM interaction with the Azure Fabric Controller. Due to the particularity of RancherOS, some functions of `waggent` are limited.

###  Known limitations:
- change default username
- set/reset user password
- reset user ssh key
- not supported `VM Extension`
