### ISSUE TITLE
Improve the vsphere experience in Rancher when using RancherOS

### ISSUE THREAD

**Issue by niusmallnan** [rancher/os#2808]
To-do list:
1.  The docker engine can be switched when the local version is the same as the specified version. Related to https://github.com/rancher/rancher/issues/17895
2. The docker engine can be switched correctly when the service local cache is inconsistent with the specified version. If it can't be switched, just use the default engine. Related to https://github.com/rancher/os/issues/2710
3.  Use `overlay2` as the default storage driver.
4. Provide an airgap install guide. In this case, users will use local os-serivice, local private registry or mirror.

**Comment by kingsd041** [comment]
> 1.  The docker engine can be switched when the local version is the same as the specified version. Related to https://github.com/rancher/rancher/issues/17895       

Version: rancheros v1.5.3-rc1
Confirmed fix. In the airgap or online environment, and the local version and the specified version are the same, you can use the rancheros v1.5.3-rc1 to switch the docker engine.


> 2. The docker engine can be switched correctly when the service local cache is inconsistent with the specified version. If it can't be switched, just use the default engine. Related to https://github.com/rancher/os/issues/2710

Version: rancheros v1.5.3-rc1
Confirmed fix. 


> 4. Provide an airgap install guide. In this case, users will use local os-serivice, local private registry or mirror.

In airgap network, rancheros cannot be launched using docker-machine or [Creating vSphere Clusters](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/). Because using docker-machine to launch rancheros requires pull the `open-vm-tools` image from system-docker. Configuring the system-docker registration certificate according to the [airgap documentation](https://github.com/rancher/docs/pull/1543/files) requires restarting rancheros to take effect, so pull the `open-vm-tools` image in the arigap network fails.
Similarly, if you launch rancheros using [Creating vSphere Clusters](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/), you will not be able to pull `rancher/os-docker` from system-docker.

**Comment by niusmallnan** [comment]
In the airgap environment, users usually use such a cloud-config:
```
rancher:
  environment:
    REGISTRY_DOMAIN: xxxx.yyy
  repositories:
    core:
      url: https://foo.bar.com/os-services
```
Then system-docker needs to pull `xxxx.yyy/rancher/openvm-tools`. If system-docker does not have a valid certificate, it will not be able to pull this image. 

Usually, most users use a custom certificate. So we need to provide a way to set a custom certificate for system-docker.

I added a script that can flush the custom certs to the ISO file. https://github.com/rancher/os/blob/master/scripts/tools/flush_crt_iso.sh
We can rebuild a new ISO which includes the custom certs: 
```
make shell-bind
cd scripts/tools/
wget http://link/rancheros-xx.iso
wget http://link/custom.crt
./flush_crt_iso.sh --iso rancheros-xx.iso --cert custom.crt
exit

ls ./build/
```

**Comment by kingsd041** [comment]
After using this script to insert a custom certificate, airgap works fine.

**Comment by niusmallnan** [comment]
Close this issue as all fixes in ROS was done.
I will push the merger of other PRs.
