### ISSUE TITLE
ROS attempting to start service open-vm-tools on boot before nameservers set by DHCP

### ISSUE THREAD

**Issue by axeal** [rancher/os#2887]
In an air-gapped cluster with IP and DNS servers set by DHCP, if you enable the open-vm-tools service, then upon boot ROS will attempt to start the service and pull the image before the DNS servers have necessarily been updated by DHCP. As a result the default Google public DNS resolvers are used, which being unreachable, results in the service failing to start.

**RancherOS Version: (ros os version)**

v1.5.4

**Where are you running RancherOS? (docker-machine, AWS, GCE, baremetal, etc.)**

VMWare

**Comment by bd8392** [comment]
Maybe #2882 same error?

**Comment by janeczku** [comment]
I think that in VMware environments you are supposed to use the `rancheros-vmware` release artifacts since they have the open-vm-tools already bundled and won't require downloading them.

Starting open-vm-tools *after* DHCP will actually lead to a couple of new problems, for example:
- Longer boot times in environments without DHCP (as it will wait to acquire DHCP lease)
- cloud-config network configuration provided by Guest-Info mechanism will not be applied to DHCP client
- probably others

**Comment by bd8392** [comment]
Maybe this works for you also: https://github.com/rancher/os/issues/2882#issuecomment-533183877

**Comment by kingsd041** [comment]
Tested with RancherOS v1.5.5-rc1

> If it is already built-in, we should use tag image
> use case: open-vmtools with another REGISTRY_DOMAIN setting

Install rancheros to disk using yaml below
```
#cloud-config
rancher:
  environment:
    EXTRA_CMDLINE: /init
    REGISTRY_DOMAIN: rancher.kingsd.top
```

After waiting for Rancheros to restart, confirm that the image used by open-vm-tools is `rancher.kingsd.top/rancher/os-openvmtools: 10.3.10-2`
