### ISSUE TITLE
No ssh / ping after boot

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#406]
First once in a while I get no ping / ssh after booting up RancherOS, but at the moment each time I boot I cant ping / ssh the machine. I assume I get no dhcp ip (static lease), but can't check it. Serial console output ends with the / before I see the RancherOS bootloader.

**Comment by pwFoo** [comment]
Changed dhcp to static ip and it seems to work again. So it should be a RancherOS dhcpcd problem.

**Comment by imikushin** [comment]
Can you confirm this is present on RancherOS v0.3.3?

**Comment by pwFoo** [comment]
Haven't tested it after upgrade, because without a serial console output I can't change it back if dhcp isn't working ;)

And after upgrade to 0.3.3 rancher/agent isn't working deleted old agent, registered a new host and agent is dying after 8-10 seconds.

So I have to do some other tests and if I plan a reinstall I'll do a dhcp test before.

**Comment by imikushin** [comment]
@pwFoo Can you describe your operating environment where you run RancherOS? Also, the steps to reproduce. The issue might be intermittent, but we would appreciate any details to try to reproduce.

**Comment by pwFoo** [comment]
Hi,
it runs on [APU board](http://www.pcengines.ch/apu.htm) with 4GB RAM for testing.

**Comment by pwFoo** [comment]
Maybe a problem with static dhcp lease? #540

**Comment by deniseschannon** [comment]
@pwFoo Are you still having this issue with v0.4.3? We made major networking changes since v0.3.3 so not sure if this is still an issue.

**Comment by pwFoo** [comment]
Hi @deniseschannon,

I can't reproduce it at the moment. Maybe it's gone.
I think issue could be closed.

**Comment by iDiogenes** [comment]
Hello @deniseschannon, I realize this issue was just closed, but I seem to be experencing similar behavior on v0.4.3. DHCP is only working if I wait about 30 seconds after boot before plugging in ethernet cable. If I leave it in during boot, it can sometimes take 30 min+ before the system finally comes up.

I am using a bare-metal install on a Soekris net6501-70 and like @pwFoo the unit is console only, so I am unable to see the details once grub takes over.
