### ISSUE TITLE
How to Assign IP on OS and a container

### ISSUE THREAD

**Issue by sjkeerthi** [rancher/os#434]
Hi All,

I have a quick question with reference to the docker doc I could see there is a possible way to assign the my own network IP address into the docker0 interface.

My Requirement is there a possible way to assign my own real routable ip address to my container so that I can access directly container with real IP.

If there is no such a way I would like to bring up an idea that once I install the RancherOS I should have an option once I added via RancherUI and should able to define the routable IP address to docker0 interface so that I can assign real network to my containers.

**Comment by ibuildthecloud** [comment]
@sjkeerthi I think this gets a bit more complicated.  The way people typically do this is as follows.

1. Create docker0
2. Add eth0 to docker0
3. Configure docker0 with IP of host (or DHCP) and remove IP from eth0
4. Configure `Docker daemon` to use a block of IPs on your subnet but reserved for the host.

Is what you are looking to do?  Step 4 gets tricky because this is a manual configuration and has to be managed as you add more hosts.

**Comment by sjkeerthi** [comment]
Is there any doc for reference. I love to go Rancher on my company for production.

I want all my containers to assign routable ip where I can access with that ip directory

**Comment by SvenDowideit** [comment]
related to #436
