### ISSUE TITLE
[INFO] RancherOS VS Alpinelinux

### ISSUE THREAD

**Issue by Micka33** [rancher/os#466]
Hi guys !

I'm about to migrate my services to dockers. I looked at different specialized OS's (phusion/base-image, etc) and 2 remain:
 - [RancherOS](http://rancher.com/rancher-os/)
 - [Alpinelinux](https://www.alpinelinux.org/about/)

I have a hard time making the cons and pros between the two. Alpinelinux seems to have a focus on security, while rancheros has an API that allows Rancher to nicely plug all of it.
 - But I might be able to use Alpine with Rancher as well?
 - and having a container made OS should also increase security in a way ?

--
> Alpine Linux was designed with security in mind. The kernel is patched with grsecurity/PaX out of the box, and all userland binaries are compiled as Position Independent Executables (PIE) with stack smashing protection. These proactive security features prevent exploitation of entire classes of zero-day and other vulnerabilities.

--
> RancherOS, on the other hand, is designed from the ground up to leverage the Docker API and host sophisticated management agents so they can be managed at large scale in production by container management platforms like Rancher.

**Comment by Xe** [comment]
You can make an alpine container in RancherOS easily. Alpine is a more traditional linux distro than RancherOS is.

**Comment by pwFoo** [comment]
I like RancherOS, but docker host could be managed easier with Alpine (ssh, users, interfaces, firewall, additional pppoe connection, ...).

Any cons against Alpine as host OS instead of RancherOS?

**Comment by Xe** [comment]
Alpine is good if you are more used to a conventional server management workflow. However if you are treating your servers literally like cattle, RancherOS is perfect.

**Comment by pwFoo** [comment]
Because I need a special network setting
* host 1 with /32 ip, static route to default gw
* host 2 with pppoe wan and internal (docker interface)

and some other reasons
* ssh login without pubkey via serial console
* basic firewalling to secure external interface 

Alpine seems to be easier to manage. With RancherOS I have to build a network container to set up the pppoe connection without break the RancherOS network settings.

**Comment by deniseschannon** [comment]
@Micka33 If you still want more discussion, please re-open. :)

**Comment by MikePadge** [comment]
@deniseschannon I'd like to re-open this discussion here, especially with the time that has passed, and now because we can throw k3s into the mix. That's actually how I wound up here. Do I run k3s on a bunch of old hardware running RancherOS or another host system. 

What is the hostOS Rancher team uses, and what various hostOSs have your clients had success with?

**Comment by ibuildthecloud** [comment]
@MikePadge k3s isn't specifically tied to any particular OS so you are really free to choose what you may.  RancherOS currently is very oriented towards running Docker containers.  You can run k3s on RancherOS as a Docker container and it will work fine.  But it doesn't currently mean that RancherOS is better at running k3s than any other OS because there is no specific integration between the two.  So I'd say the only reason why you'd run k3s on RancherOS is because you like RancherOS itself, not because the integration of the two is better.

At Rancher we of course mostly run RancherOS for our production systems and we run k3s on RancherOS [more info](https://github.com/rancher/k3s/issues/73#issuecomment-469413149).

We are starting the effort now to make a new version of RancherOS that is optimized for k3s.  That could be RancherOS 2.x or something else.  At that point when we do release that, it will probably be the simplest way to manage an OS for k3s.

**Comment by pwFoo** [comment]
Instead of k3s optimized image I would like a more universal RancherOS build for all use cases. Minimal footprint, minimal boot time. Typical kernel modules also für desktop usage?

**Comment by liyimeng** [comment]
@ibuildthecloud excited! Roadmap? Timeline? ;)

**Comment by rbucker** [comment]
This issue was close but I wanted to add my nickle. RancherOS is not totally immutable and unles you install the ubuntu or alpine console you cannot install anything at all. The point being is that Rancher could be considered a light's out distro. Meaning that you should NEVER update it in place because at some point you may forget the steps you took to get there and so everything should be upgraded by deploying it fresh. (consider the CI/CD model of compiling your artifacts and deploying from a runner)

**Comment by rbucker** [comment]
separate question... will alpinelinux install from alpinelinux iso with docker-machine?
