### ISSUE TITLE
Can't run docker following upgrade

### ISSUE THREAD

**Issue by Rucknar** [rancher/os#564]
Upgraded as per docs from 0.4.0-RC2 to 0.4.0-RC5. Upgrade went smoothly but we can't run the docker command. I appreciate this is an RC so happy to rebuild if required. Errors as i see them:

```
[rancher@PTL-DOC-04 rancher]$ sudo system-docker ps
FATA[0000] no such file or directory
[rancher@PTL-DOC-04 rancher]$ docker ps
-bash: docker: command not found
[rancher@PTL-DOC-04 rancher]$ ps -ef | grep docker
    1 root     docker daemon --log-opt max-size=25m --log-opt max-file=2 -s overlay -b docker-sys --fixed-cidr 172.18.42.1/16 --restart=false -g /var/lib/system-docker -G root -H unix:///var/run/system-docker.sock --userland-proxy=false
 1008 rancher  grep docker
[rancher@PTL-DOC-04 rancher]$
```

**Comment by deniseschannon** [comment]
We don't expect upgrades to work between "rc" releases as we are still going through rounds of testing. In v0.4.0, due to the refactoring and changes, we will not be supporting upgrading from v0.3.3 to v0.4.0 (when we release). After v0.4.0 is officially released, we will support upgrades to the next version.
