### ISSUE TITLE
Calico / weave docker plugins as os-services

### ISSUE THREAD

**Issue by pwFoo** [rancher/os#585]
Add weave and prefered calico libnetwork plugins to RancherOS?

**Comment by pwFoo** [comment]
https://github.com/projectcalico/calico-docker/blob/master/docs/getting-started/libnetwork/Demonstration.md

**Comment by pwFoo** [comment]
Weave could be deployed with an prebuild image, but I try to test calico libnetwork.

After calico/node-libnetwork is started I try to start containers for testing using the calico docker plugin. During docker run command I get the following message

```
flag provided but not defined: --publish-service
```

Is the **--publish-service** flag not provided by the RancherOS docker version? Or is it another problem with my calico setup?

**Comment by pwFoo** [comment]
Tested with 
- RancherOS 0.4
- Engine Version: 1.9.0-dev

> docker network create --driver=calico --subnet=192.168.0.0/24 net1
> Error response from daemon: error getting pools config from store during init: store for addres space GlobalDefault not found

But could also be a calico problem.

**Comment by CooCooCaCha** [comment]
Does Calico need Etcd running?

**Comment by pwFoo** [comment]
Yes. I tried this etcd container solution.
https://github.com/coreos/etcd/blob/master/Documentation/docker_guide.md

**Comment by CooCooCaCha** [comment]
It looks like the docker daemon in RancherOS needs to be started with clustering flags
https://github.com/docker/docker/pull/16910#issuecomment-147477253

**Comment by faddat** [comment]
I've been playing with RancherOS & weave myself, reason being that Rancher doesn't seem to be getting through my NAT any more.  I've got 5 machines @ Google Compute Engine and 10 local.  It also looks like weave could be useful for reverse proxying things out of the local machines onto a public endpoint @ google.  

It'd be neat if I could have 1 or 2 (2nd for redundancy only) endpoints for my cluster that all exit via the system configured by rancher external DNS.  I'm thinking possibly on the master node since I tend to make that a node that is widely exposed.  

I don't know if you guys have seen weave scope?  Their great UI made me think of your great UI, and I did suggest to their team that you guys collaborate in some fashion or another.

**Comment by voobscout** [comment]
@faddat Mind explaining how to run weave as a service on rancherOS?

```yaml
weave:
  image: your-weave-container
  container_name: weave
  privileged: true
  labels:
    io.rancher.os.scope: system
    io.rancher.os.after: docker,console
  volumes_from:
    - all-volumes
  net: host
```

more precisely how to make a container for weave? a Dockerfile would be awesome or some general advice would be much appreciated. Thanks!

**Comment by faddat** [comment]
Hey in the provided example, what should I do about the fact that weave runs from a script, eg:
```
sudo curl -L git.io/weave -o /usr/local/bin/weave
sudo chmod a+x /usr/local/bin/weave
```
/usr/local/bin/weave is a shell script that controls-- if I am not mistaken-- three docker images and the docker plugin.  

Thanks guys!

-Jake

**Comment by pwFoo** [comment]
Created a convoy system-docker service.
You can read about here:
https://github.com/rancher/os/issues/706

The problem is the mapping from within a container to the console (also a container).

**Comment by deniseschannon** [comment]
We won't be adding these system-services in directly, but there is an example of weave in this issue that should work.

**Comment by faddat** [comment]
Trouble I had with weave specifically was that I don't know how to get it
going smoothly without its "weave" script.  I'll report back in a bit :).
