### ISSUE TITLE
Security groups for AWS/EC2

### ISSUE THREAD

**Issue by JulianKingman** [rancher/os#607]
I'm new to AWS and am trying to wrap my head around security groups. All the RancherOS docs have to say about it is "configure security group", but what settings should I use? Should I have everything open so I can route ports freely within Rancher, or do I only need certain ports open? I guess I'm looking for the 'best practice' here.

If it helps to know what I'll be doing, I'll be running multiple containers with Wordpress (Wordpress, nginx, mysql) and Meteor (meteor, mongodb). My plan is to have multiple domains route through to rancher.

**Comment by deniseschannon** [comment]
Configuring your security group is really up to the user and how you plan on using your host.

For example, if you are running Rancher, you need port `8080` to be open so that the UI can be seen. You can also set a different port for the UI if you wanted.

If you are running Rancher agent (aka running it as a host), you'll need to add UDP ports `500` and `4500` to be open so that IPsec tunneling for the managed network to work. 

For all of your applications (ie. wordpress, meteor), you'll need to open whatever ports that you decide to expose on the host so that it can be accessed.

**Comment by JulianKingman** [comment]
Thanks! In my case I needed 8080, 500, 4500, and 80 (for Wordpress).
