### ISSUE TITLE
'console' restart - container impact

### ISSUE THREAD

**Issue by Rucknar** [rancher/os#727]
Our monitoring through prometheus connected to cadvisor highlighted the rancher console container to be our most CPU intensive (user & system) running on our hosts, as a result i decided to restart the container in-case any old sessions left running commands etc could be causing the high CPU. 

This went badly, the IPSEC tunnel between my hosts failed, as did the network agent on that host, this in-turn caused a service outage on our environment as we only have two active hosts, health checks failed and services were frantically restarted my rancher until i could re-establish the racoon tunnel between hosts. 

My expected behaviour is that a restart of the console component would have no impact aside from disconnecting any logged in SSH sessions. 

```
Rancher	v0.50.1
Cattle	v0.127.0
User Interface	v0.74.0
Rancher Compose	v0.6.2
```

**Comment by Rucknar** [comment]
@ibuildthecloud Has explained this is by design as it's how the docker daemon is run. Feel free to re-open the ticket if that's something that wants to be changed but i'll close it for now and update our docs.

**Comment by ibuildthecloud** [comment]
It is possible to reconfigure docker to not use the console container but this is what most user expect.  The reason is because of bind mounts.  Most people expect that when they do `-v /foo:/foo` it will use `/foo` that they see with `ls /foo` in the console.

This means that Docker must use the mount context of the console.
